# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180828_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.Category', verbose_name='所属分类'),
        ),
    ]
