# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 03:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20180829_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
